# Generated by Django 4.2.16 on 2025-05-27 22:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import documents.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the PDF document', max_length=200)),
                ('pdf_file', models.FileField(help_text='Upload PDF file only', upload_to=documents.models.pdf_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('parent_card_id', models.IntegerField(choices=[(1, 'Parent Card 1'), (2, 'Parent Card 2'), (3, 'Parent Card 3'), (4, 'Parent Card 4'), (5, 'Parent Card 5'), (6, 'Parent Card 6'), (7, 'Parent Card 7'), (8, 'Parent Card 8'), (9, 'Parent Card 9'), (10, 'Parent Card 10')], help_text='Parent card number (1-10)')),
                ('subcard_id', models.IntegerField(choices=[(1, 'Subcard 1'), (2, 'Subcard 2'), (3, 'Subcard 3'), (4, 'Subcard 4'), (5, 'Subcard 5'), (6, 'Subcard 6'), (7, 'Subcard 7'), (8, 'Subcard 8'), (9, 'Subcard 9'), (10, 'Subcard 10')], help_text='Subcard number (1-10)')),
                ('uploaded_by', models.ForeignKey(help_text='User who uploaded this document', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PDF Document',
                'verbose_name_plural': 'PDF Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
