# Generated by Django 4.2.16 on 2025-05-28 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_parent_cards', models.IntegerField(default=10)),
                ('max_subcards', models.IntegerField(default=10)),
            ],
            options={
                'verbose_name': 'Card Settings',
                'verbose_name_plural': 'Card Settings',
            },
        ),
        migrations.AlterField(
            model_name='pdfdocument',
            name='parent_card_id',
            field=models.IntegerField(help_text='Parent card number'),
        ),
        migrations.AlterField(
            model_name='pdfdocument',
            name='subcard_id',
            field=models.IntegerField(help_text='Subcard number'),
        ),
    ]
